class ContactAlreadyExistsError(Exception):
    pass


class ContactNotExistsError(Exception):
    pass
